/*
File:    macro_build_worker_level_data.sas
Purpose: Construct the worker-level hierarchy and labor-cost data used for Figure 2.
Usage:   Run through the stage or package driver unless the README says otherwise.
*/

%macro worker_level;
%let year=2002;
data dataA; set a.t&year.;
run;
data dataA; set dataA;
	if filt eq '1';
	if missing(cs) ne 1;
	if age >= 16; if age <= 65;
	if domempl in ('2','9');
	if substr(catjur,1,1) = '5';
	if cpfd in ('P','C');
	if s_net < s_brut;
	if missing(s_brut) eq 0;
run;
data dataA; set dataA;
	if cda not in ('A');
	if typ_emploi in ('O');
run;
data dataA; set dataA;
	if substr(cs,1,1) in ('2','3','4','5','6');
run;
data dataA; set dataA;
    if missing(nbheur) eq 0;
	if nbheur > 0;
run;
data gmrsiren; set outp.firm_rtt_2002_final;
	keep siren GMR annee_rtt
    mois_rtt typeacc
	min_an e_eqtp_AAide e_eqtp_ent mdo mrtt apet siret large_f;
run;
data gmrsiren; set gmrsiren;
	rename apet  = apet_acc;
	rename siret = siret_acc;
run;
proc sort data = gmrsiren; by siren; run;
proc sort data = dataA; by siren; run;
data dataA; merge dataA gmrsiren; by siren; run;
data dataA; set dataA;
	if missing(age) ne 1;
run;
data t&year.; set dataA;
	if typeacc = 100 then typeacc = .;
	if min_an  = 100 then min_an  = .;
	apet_year = apet;
	mois_aide  = mois_rtt;
	annee_aide = annee_rtt;
	if gmr = 6 then annee_aide = .;
	if gmr = 6 then mois_aide  = .;
	if gmr = 6 then typeacc    = .;
	if typeacc = 9 then annee_aide = .;
	if typeacc = 9 then mois_aide = .;
run;
data t&year.; set t&year.;
	apet = apet_acc;
run;
%calcot(&year.);
%rist(&year.);
data dataA; set t&year.;
	cspa_net   = max(cspa - exo_a,0);
	s_supbrut  = s_brut + cspa_net ;
	if missing(typeacc) eq 1 then typeacc = 100;
	if missing(min_an)  eq 1 then min_an  = 100;
	apet = apet_year;
run;
data dataA; set dataA;
	drop apet_year;
run;
proc datasets library = work;
	delete t&year.;
run;
data dataA; set dataA;
	MAX_H = (&year. > annee_rtt) * 152 + (&year. < annee_rtt) * 169
			+ (&year. = annee_rtt) * 169 * mois_rtt/12
			+ (&year. = annee_rtt) * 152 * (12 - mois_rtt)/12;
	if (cpfd= "C") then e_eqtp_vrtt = min(1,duree/360) ;
	else if nbheur = 0 then e_eqtp_vrtt = min(1,duree/360);
	else e_eqtp_vrtt = max(0,min(1,nbheur/(MAX_H * 12)));
	s_brut_h = sbh;
	if (nbheur>0) then s_supbrut_h = s_supbrut/nbheur; else s_supbrut_h = 1000000;
run;
data dataA; set dataA;
	codgeo = comt;
run;
data dataA; set dataA;
	drop comt;
run;
data dataA; set dataA;
	rename codgeo = comt;
run;
/* From this point Figure 2 needs only firm id, occupation, and hourly total labor cost. */
data dataB; set dataA;
	keep siren domempl cs s_supbrut_h;
run;
data dataB; set dataB;
	year = &year.;
	if missing(domempl) ne 1;
run;
data dataB; set dataB;
	cs1 = '0';
	if substr(cs,1,1) eq '0' then cs1 = '0';
	if substr(cs,1,1) eq '1' then cs1 = '1';
	if substr(cs,1,1) eq '2' then cs1 = '2';
	if substr(cs,1,1) eq '3' then cs1 = '3';
	if substr(cs,1,1) eq '4' then cs1 = '4';
	if substr(cs,1,1) eq '5' then cs1 = '5';
	if substr(cs,1,1) eq '6' then cs1 = '5';
	if cs1 = '5' then lyr = 1;
	if cs1 = '4' then lyr = 10;
	if cs1 = '3' then lyr = 100;
	if cs1 = '2' then lyr = 1000;
run;
proc sort data = dataB; by siren cs1; run;
proc means data = dataB noprint;
	by siren cs1;
	var lyr;
	output out    = totallayers (drop = _type_ _freq_)
	max           = totlyr;
run;
proc means data = totallayers noprint;
	by siren;
	var totlyr;
	output out    = totallayers (drop = _type_ _freq_)
	sum           = totlyr;
run;
data totallayers; set totallayers;
	layerlenient       = 30;
run;
data totallayers; set totallayers;
	if totlyr = 1111 then layerlenient = 3;
	if totlyr =  111 then layerlenient = 2;
	if totlyr = 1011 then layerlenient = 2;
	if totlyr = 1101 then layerlenient = 2;
	if totlyr = 1110 then layerlenient = 2;
	if totlyr = 1001 then layerlenient = 1;
    if totlyr = 1010 then layerlenient = 1;
	if totlyr = 1100 then layerlenient = 1;
	if totlyr =  101 then layerlenient = 1;
	if totlyr =  110 then layerlenient = 1;
	if totlyr =   11 then layerlenient = 1;
	if totlyr =    1 then layerlenient = 0;
	if totlyr =   10 then layerlenient = 0;
	if totlyr =  100 then layerlenient = 0;
	if totlyr = 1000 then layerlenient = 0;
run;
proc sort data = totallayers; by siren; run;
proc sort data = dataB; by siren; run;
data dataB; merge dataB totallayers; by siren;
if cs1 = '2' then LAYER = layerlenient;
else if cs1 = '3' then do;
	if totlyr <  1000 then LAYER = layerlenient;
	if totlyr >= 1000 then LAYER = layerlenient - 1;
end;
else if cs1 = '4' then do;
	if totlyr <   100 then LAYER = layerlenient;
	if totlyr in (1010, 1011, 110, 111) then LAYER = layerlenient - 1;
	if totlyr in (1110, 1111) then LAYER = layerlenient - 2;
end;
else if cs1 = '5' then do;
	if totlyr <    10 then LAYER = layerlenient;
	if totlyr in (1001, 101, 11) then LAYER = layerlenient - 1;
	if totlyr in (1101, 1011, 111) then LAYER = layerlenient - 2;
	if totlyr in (1111) then LAYER = layerlenient - 3;
end;
run;
proc datasets library = work;
	delete totallayers;
run; quit;
/* The Figure 2 program consumes only firm id, hourly labor cost, and hierarchy assignments. */
data dataB; set dataB;
	keep siren s_supbrut_h layerlenient LAYER;
run;
proc datasets lib = work memtype = data;
	modify dataB;
	attrib _all_ label = '';
	attrib _all_ format = ;
run;
	PROC EXPORT DATA = dataB
		OUTFILE = "&root\output\generated\Output_data\For_4_SAS_ORGANIZATIONS\STATA\Dworkerlevel_lp02&year..dta"
		DBMS = DTA LABEL REPLACE;
	RUN;
proc datasets library = work;
	delete dataA   gmrsiren gmr;
run;
%mend;
%worker_level; run; quit;
