/*
File:    macro_build_firm_rtt_history.sas
Purpose: Merge working-time-reduction histories with simulated labor costs and firm characteristics.
Usage:   Run through the stage or package driver unless the README says otherwise.
*/

%macro firm_rtt_2002;
%let listyear2  = %str(1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008);
%let countyear1 = %sysfunc(countw(&listyear2));
%do zz = 1 %to &countyear1;
	%let year2 = %scan(&listyear2,&zz,%str(,));
data data&year2.; set sim.simul_mw_&year2.;
	an = &year2.;
	year = &year2.;
run;
%if %superq(keep_intermediate) ne 1 %then %do;
proc datasets library=sim nolist; delete simul_mw_&year2.; quit;
%end;
data data&year2.;
length siren $ 9;
set data&year2.;
	siren = substr(siret,1,9);
run;
%if %eval(&year2.) < 2008  %then %do;
data data&year2.;
length apet2 $ 5;
set data&year2.;
	apet2 = substr(apet,1,4);
run;
%end;
%if %eval(&year2.) >= 2008  %then %do;
data data&year2.;
length apet2 $ 5;
set data&year2.;
	apet2 = substr(apet,1,5);
run;
%end;
data data&year2.; set data&year2.;
	drop apet;
run;
data data&year2.; set data&year2.;
	rename apet2 = apet;
run;
data firm_info&year2.; set outp.firm_info&year2.;
	drop siren apet;
run;
proc sort data = firm_info&year2.; by siret; run;
proc sort data = data&year2.; by siret; run;
data data&year2.; merge data&year2. firm_info&year2.; by siret; run;
data data&year2.; set data&year2.;
	if missing(an) ne 1;
run;
proc datasets library = work;
	delete firm_info&year2.;
run;
%if %superq(keep_intermediate) ne 1 %then %do;
proc datasets library=outp nolist; delete firm_info&year2.; quit;
%end;
%end;
data dataA; set data1995 data1996 data1997 data1998 data1999 data2000 data2001 data2002 data2003 data2004 data2005 data2006 data2007 data2008;
	apet_alt = 6;
	if apet = "602M" then apet_alt = 1;
	if substr(apet,1,2) = "55" then apet_alt = 2;
	if substr(apet,1,2) = "17" then apet_alt = 3;
	if substr(apet,1,2) = "18" then apet_alt = 4;
	if substr(apet,1,2) = "19" then apet_alt = 5;
	if e_eqtp_AAide <= 20 then e_eqtp_AAide = 20;
	if e_eqtp_AAide > 20  then e_eqtp_AAide = 21;
	if e_eqtp_ent >= 20 then e_eqtp_ent = 20;
	if e_eqtp_ent < 20  then e_eqtp_ent = 19;
    if missing(typeacc) eq 1 then typeacc = 100;
	if missing(min_an)  eq 1 then min_an  = 100;
	large_f = 0;
	if totpostes_siren >  20 then large_f = 1;
	if totpostes_siren <= 20 then large_f = 0;
run;
data dataB; set dataA; run;
/* Preserve the submitted sort order used for deterministic tie breaking, while omitting the diagnostic statistics formerly calculated between these sorts. */
proc sort data=dataB; by siren year; run;
proc sort data=dataB; by siren annee_rtt; run;
proc sort data=dataB; by siren; run;
/* Diagnostics that did not affect RTT/GMR selection or any retained output are omitted. */
data dataB; set dataB;
	dist02 = 0;
	if an = 2002 then dist02 = 2002-2002;
	if an < 2002 then dist02 = (an-2002)*(-1);
	if an > 2002 then dist02 = (an-2002) + (2002-1995);
run;
data no_accord_firm; set dataB;
	E = 1;
	D = 0;
run;
data no_accord_firm; set no_accord_firm;
	if typeacc eq 100 then D = 1;
run;
proc sort data = no_accord_firm; by siren; run;
proc means data = no_accord_firm noprint;
		by siren;
		var E D;
		output out = totE (drop = _type_ _freq_)
		sum        = totE totD;
run;
proc sort data = dataB; by siren; run;
proc sort data = totE; by siren; run;
data dataB; merge dataB totE; by siren; run;
proc datasets library = work;
	delete totE no_accord_firm;
run;
data dataB; set dataB;
	if totE = totD or typeacc ne 100;
run;
proc sort data = dataB; by siren dist02; run;
proc means data = dataB noprint;
		by siren;
		var dist02;
		output out = min_dist02 (drop = _type_ _freq_)
		min        = min_dist02;
run;
proc sort data = dataB; by siren; run;
proc sort data = min_dist02; by siren; run;
data dataB; merge dataB min_dist02; by siren; run;
data dataB; set dataB;
	if min_dist02 = dist02;
run;
data dataB; set dataB;
	share_postes = totpostes_siret/totpostes_siren;
run;
proc sort data = dataB; by siren; run;
proc means data = dataB noprint;
		by siren;
		var share_postes;
		output out = max_share_postes (drop = _type_ _freq_)
		max        = max_share_postes;
run;
proc sort data = dataB; by siren; run;
proc sort data = max_share_postes; by siren; run;
data dataB; merge dataB max_share_postes; by siren; run;
data dataB; set dataB;
	if max_share_postes = share_postes;
run;
data b; set dataB;
	E = 1;
run;
proc sort data = b; by siren; run;
proc means data = b noprint;
		by siren;
		var E;
		output out = totobs (drop = _type_ _freq_)
		sum        = totobs;
run;
proc sort data = b; by siren typeacc; run;
proc means data = b noprint;
		by siren typeacc;
		var E;
		output out = totobs_typeacc (drop = _type_ _freq_)
		sum        = totobs_typeacc;
run;
proc sort data = b; by siren gmr; run;
proc means data = b noprint;
		by siren gmr;
		var E;
		output out = totobs_gmr (drop = _type_ _freq_)
		sum        = totobs_gmr;
run;
proc sort data = dataB; by siren; run;
proc sort data = totobs; by siren; run;
data dataB; merge dataB totobs; by siren; run;
proc sort data = dataB; by siren typeacc; run;
proc sort data = totobs_typeacc; by siren typeacc; run;
data dataB; merge dataB totobs_typeacc; by siren typeacc; run;
proc sort data = dataB; by siren gmr; run;
proc sort data = totobs_gmr; by siren gmr; run;
data dataB; merge dataB totobs_gmr; by siren gmr; run;
/* Probability diagnostic flags were not consumed by retained outputs. */
data dataB; set dataB;
	share_totobs_gmr = totobs_gmr/totobs;
run;
proc sort data = dataB; by siren; run;
proc means data = dataB noprint;
		by siren;
		var share_totobs_gmr;
		output out = max_share_totobs_gmr (drop = _type_ _freq_)
		max        = max_share_totobs_gmr;
run;
proc sort data = dataB; by siren; run;
proc sort data = max_share_totobs_gmr; by siren; run;
data dataB; merge dataB max_share_totobs_gmr; by siren; run;
data dataB; set dataB;
	if max_share_totobs_gmr = share_totobs_gmr;
run;
data dataB; set dataB;
	share_totobs_typeacc = totobs_typeacc/totobs;
run;
proc sort data = dataB; by siren; run;
proc means data = dataB noprint;
		by siren;
		var share_totobs_typeacc;
		output out = max_share_totobs_typeacc (drop = _type_ _freq_)
		max        = max_share_totobs_typeacc;
run;
proc sort data = dataB; by siren; run;
proc sort data = max_share_totobs_typeacc; by siren; run;
data dataB; merge dataB max_share_totobs_typeacc; by siren; run;
data dataB; set dataB;
	if max_share_totobs_typeacc = share_totobs_typeacc;
run;
proc datasets library = work;
	delete max_share_totobs_typeacc max_share_totobs_gmr;
run;
proc sort data = dataB; by siren typeacc e_eqtp_AAide e_eqtp_ent mdo mrtt apet_alt min_an large_f siret; run;
data dataB; set dataB; by siren;
	if first.siren;
run;
data dataB; set dataB;
	keep siren siret annee_rtt mois_rtt typeacc gmr apet apet_alt min_an
         e_eqtp_AAide e_eqtp_ent mdo mrtt large_f;
run;
data outp.firm_rtt_2002_final; set dataB; run;
proc datasets library = work;
	delete b min_dist02 max_share_postes totobs totobs_gmr totobs_typeacc;
run;
%let listyear2  = %str(1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008);
%let countyear1 = %sysfunc(countw(&listyear2));
%do zz = 1 %to &countyear1;
	%let year2 = %scan(&listyear2,&zz,%str(,));
%firm_info_sim(&year2.);
data dataC; set firm_info_sim&year2.; run;
proc datasets library = work;
	delete firm_info_sim&year2.;
run;
proc sort data = dataC nodupkey; by annee_rtt mois_rtt typeacc gmr apet_alt large_f min_an e_eqtp_AAide e_eqtp_ent mdo mrtt; run;
data dataD; set dataB; run;
proc sort data = dataD; by annee_rtt mois_rtt typeacc gmr apet_alt large_f min_an e_eqtp_AAide e_eqtp_ent mdo mrtt; run;
proc sort data = dataC; by annee_rtt mois_rtt typeacc gmr apet_alt large_f min_an e_eqtp_AAide e_eqtp_ent mdo mrtt; run;
data dataD; merge dataD dataC; by annee_rtt mois_rtt typeacc gmr apet_alt large_f min_an e_eqtp_AAide e_eqtp_ent mdo mrtt; run;
data dataD; set dataD;
	if missing(siren) ne 1;
run;
data outp.firm_rtt&year2.; set dataD;
	year = &year2.;
run;
proc datasets library = work;
	delete dataD;
run;
%end;
proc datasets library = work;
	delete dataA dataB dataC data1995 data1996 data1997 data1998 data1999 data2000 data2001 data2002 data2003 data2004 data2005 data2006 data2007 data2008;
run;
%mend;
