/*
File:    macro_build_calibration_moments.sas
Purpose: Build firm-level wage-bin and minimum-wage exposure measures used in the calibration moments.
Usage:   Run through the stage or package driver unless the README says otherwise.
*/

%macro dads_calibration_moments2;
%let year=2006;
data dataA; set a.t&year.;
run;
data dataA; set dataA;
	if filt eq '1';
	if missing(cs) ne 1;
	if age >= 16; if age <= 65;
	if domempl in ('2','9');
	if substr(catjur,1,1) = '5';
	if cpfd in ('P','C');
	if s_net < s_brut;
	if missing(s_brut) eq 0;
run;
data dataA; set dataA;
	if cda not in ('A');
	if typ_emploi in ('O');
run;
data dataA; set dataA;
	if substr(cs,1,1) in ('2','3','4','5','6');
run;
data dataA; set dataA;
    if missing(nbheur) eq 0;
	if nbheur > 0;
run;
data gmrsiren; set outp.firm_rtt_2002_final;
	keep siren GMR annee_rtt
    mois_rtt typeacc
	min_an e_eqtp_AAide e_eqtp_ent mdo mrtt apet siret large_f;
run;
data t&year.; set gmrsiren;
	an = &year.;
	mois_aide  = mois_rtt;
	annee_aide = annee_rtt;
	if gmr = 6 then annee_aide = .;
	if gmr = 6 then mois_aide  = .;
	if gmr = 6 then typeacc    = .;
	if typeacc = 9 then annee_aide = .;
	if typeacc = 9 then mois_aide = .;
	C = 1;
	GMR1 = 0;
	GMR2 = 0;
	GMR3 = 0;
	GMR4 = 0;
	GMR5 = 0;
	GMR6 = 0;
	if gmr = 1 then GMR1 = 1;
	if gmr = 2 then GMR2 = 1;
	if gmr = 3 then GMR3 = 1;
	if gmr = 4 then GMR4 = 1;
	if gmr = 5 then GMR5 = 1;
	if gmr = 6 then GMR6 = 1;
	if min_an   = 1994 then min_an = .;
run;
data gmr; set _policy_schedule;
	if an ne &year. then delete;
	C = 1;
	smic_brut = (6 * 169 * smic_h1 + 6 * 169 * smic_h2)/12;
    smic_brut_large = (6 * 152 * smic_h1 + 6 * 152 * smic_h2)/12 + (6 * 17 * 1.25 * smic_h1 + 6 * 17 * 1.25 * smic_h2)/12;
    smic_brut_small = (6 * 152 * smic_h1 + 6 * 152 * smic_h2)/12 + (6 * 17 * 1.10 * smic_h1 + 6 * 17 * 1.10 * smic_h2)/12;
	gmr1_brut = (6 * gmr1_m1 + 6 * gmr1_m2)/12;
	gmr2_brut = (6 * gmr2_m1 + 6 * gmr2_m2)/12;
	gmr3_brut = (6 * gmr3_m1 + 6 * gmr3_m2)/12;
	gmr4_brut = (6 * gmr4_m1 + 6 * gmr4_m2)/12;
	gmr5_brut = (6 * gmr5_m1 + 6 * gmr5_m2)/12;
	keep C smic_brut gmr1_brut gmr2_brut gmr3_brut gmr4_brut gmr5_brut smic_brut_large smic_brut_small;
run;
data t&year.; merge t&year.(in = a) gmr(in = b); by C;
if (&year. >= 2000) & large_f = 1 then smic_brut = smic_brut_large;
if (&year. >= 2002) & large_f = 0 then smic_brut = smic_brut_small;
MIN_WAGE = GMR1 * gmr1_brut + GMR2 * gmr2_brut + GMR3 * gmr3_brut + GMR4 * gmr4_brut
		+ GMR5 * gmr5_brut + GMR6 * smic_brut;
if GMR6 = 1 then do; annee_rtt = 2008; mois_rtt = 6; end;
MAX_H = (&year. > annee_rtt) * 152 + (&year. < annee_rtt) * 169
			+ (&year. = annee_rtt) * 169 * mois_rtt/12
			+ (&year. = annee_rtt) * 152 * (12 - mois_rtt)/12;
if GMR6 = 1 then do; MAX_H = 169; end;
MIN_WAGE_H = MIN_WAGE / MAX_H;
	duree = 360;
	s_brut = 12 * MIN_WAGE;
	nbheur = 12 * MAX_H;
	datfin = 360;
	datdeb = 1;
	cpfd   = 'C';
	cpfd_1 = 'C';
	cs     = "65";
run;
%calcot(&year.);
%rist(&year.);
data gmrsiren; set t&year.;
	cspa_net = max(cspa - exo_a,0);
	s_supbrut_mw  = s_brut + cspa_net ;
	s_supbrut_mwm = s_supbrut_mw / 12;
	s_supbrut_mwh = s_supbrut_mw / nbheur;
	if missing(typeacc) eq 1 then typeacc = 100;
	if missing(min_an)  eq 1 then min_an  = 100;
run;
data gmrsiren; set gmrsiren;
	rename apet  = apet_acc;
	rename siret = siret_acc;
run;
data gmrsiren; set gmrsiren;
	keep siren GMR annee_rtt
    mois_rtt typeacc
	min_an e_eqtp_AAide e_eqtp_ent mdo mrtt apet_acc siret_acc large_f
	s_supbrut_mwh MAX_H MIN_WAGE_H;
run;
proc sort data = gmrsiren; by siren; run;
proc sort data = dataA; by siren; run;
data dataA; merge dataA gmrsiren; by siren; run;
data dataA; set dataA;
	if missing(age) ne 1;
run;
proc datasets library = work;
	delete gmr gmrsiren t&year.;
run;
data t&year.; set dataA;
	if typeacc = 100 then typeacc = .;
	if min_an  = 100 then min_an  = .;
	apet_year = apet;
	mois_aide  = mois_rtt;
	annee_aide = annee_rtt;
	if gmr = 6 then annee_aide = .;
	if gmr = 6 then mois_aide  = .;
	if gmr = 6 then typeacc    = .;
	if typeacc = 9 then annee_aide = .;
	if typeacc = 9 then mois_aide = .;
run;
data t&year.; set t&year.;
	apet = apet_acc;
run;
%calcot(&year.);
%rist(&year.);
data dataA; set t&year.;
	cspa_net   = max(cspa - exo_a,0);
	s_supbrut  = s_brut + cspa_net ;
	if missing(typeacc) eq 1 then typeacc = 100;
	if missing(min_an)  eq 1 then min_an  = 100;
	apet = apet_year;
run;
data dataA; set dataA;
	drop apet_year;
run;
proc datasets library = work;
	delete t&year.;
run;
data dataA; set dataA;
	if (cpfd= "C") then e_eqtp_vrtt = min(1,duree/360) ;
	else if nbheur = 0 then e_eqtp_vrtt = min(1,duree/360);
	else e_eqtp_vrtt = max(0,min(1,nbheur/(MAX_H * 12)));
	s_brut_h = sbh;
	PB = s_brut_h < MIN_WAGE_H;
    SMIC_05l = (s_brut_h < 0.5 * MIN_WAGE_H);
    SMIC_06  = (s_brut_h < 0.6 * MIN_WAGE_H) and (s_brut_h >= 0.5 * MIN_WAGE_H);
    SMIC_07  = (s_brut_h < 0.7 * MIN_WAGE_H) and (s_brut_h >= 0.6 * MIN_WAGE_H);
    SMIC_08  = (s_brut_h < 0.8 * MIN_WAGE_H) and (s_brut_h >= 0.7 * MIN_WAGE_H);
    SMIC_09  = (s_brut_h < 0.9 * MIN_WAGE_H) and (s_brut_h >= 0.8 * MIN_WAGE_H);
	SMIC_10  = (s_brut_h < 1.0 * MIN_WAGE_H) and (s_brut_h >= 0.9 * MIN_WAGE_H);
	SMIC_11a = (s_brut_h < 1.05* MIN_WAGE_H) and (s_brut_h >= 1.0 * MIN_WAGE_H);
	SMIC_11b = (s_brut_h < 1.1 * MIN_WAGE_H) and (s_brut_h >= 1.05* MIN_WAGE_H);
	SMIC_12  = (s_brut_h < 1.2 * MIN_WAGE_H) and (s_brut_h >= 1.1 * MIN_WAGE_H);
	SMIC_13  = (s_brut_h < 1.3 * MIN_WAGE_H) and (s_brut_h >= 1.2 * MIN_WAGE_H);
	SMIC_14  = (s_brut_h < 1.4 * MIN_WAGE_H) and (s_brut_h >= 1.3 * MIN_WAGE_H);
	SMIC_15  = (s_brut_h < 1.5 * MIN_WAGE_H) and (s_brut_h >= 1.4 * MIN_WAGE_H);
	SMIC_16  = (s_brut_h < 1.6 * MIN_WAGE_H) and (s_brut_h >= 1.5 * MIN_WAGE_H);
	SMIC_17  = (s_brut_h < 1.7 * MIN_WAGE_H) and (s_brut_h >= 1.6 * MIN_WAGE_H);
	SMIC_18  = (s_brut_h < 1.8 * MIN_WAGE_H) and (s_brut_h >= 1.7 * MIN_WAGE_H);
	SMIC_19  = (s_brut_h < 1.9 * MIN_WAGE_H) and (s_brut_h >= 1.8 * MIN_WAGE_H);
	SMIC_20  = (s_brut_h < 2.0 * MIN_WAGE_H) and (s_brut_h >= 1.9 * MIN_WAGE_H);
	SMIC_20p =                                   (s_brut_h >= 2.0 * MIN_WAGE_H);
run;
data dataA; set dataA;
	if (nbheur>0) then s_supbrut_h = s_supbrut/nbheur; else s_supbrut_h = 1000000;
	SUPMWPB = s_supbrut_h < s_supbrut_mwh;
    SUPMW_05l = (s_supbrut_h < 0.5 * s_supbrut_mwh);
    SUPMW_06  = (s_supbrut_h < 0.6 * s_supbrut_mwh) and (s_supbrut_h >= 0.5 * s_supbrut_mwh);
    SUPMW_07  = (s_supbrut_h < 0.7 * s_supbrut_mwh) and (s_supbrut_h >= 0.6 * s_supbrut_mwh);
    SUPMW_08  = (s_supbrut_h < 0.8 * s_supbrut_mwh) and (s_supbrut_h >= 0.7 * s_supbrut_mwh);
    SUPMW_09  = (s_supbrut_h < 0.9 * s_supbrut_mwh) and (s_supbrut_h >= 0.8 * s_supbrut_mwh);
	SUPMW_10  = (s_supbrut_h < 1.0 * s_supbrut_mwh) and (s_supbrut_h >= 0.9 * s_supbrut_mwh);
	SUPMW_11a = (s_supbrut_h < 1.05* s_supbrut_mwh) and (s_supbrut_h >= 1.0 * s_supbrut_mwh);
	SUPMW_11b = (s_supbrut_h < 1.1 * s_supbrut_mwh) and (s_supbrut_h >= 1.05* s_supbrut_mwh);
	SUPMW_12  = (s_supbrut_h < 1.2 * s_supbrut_mwh) and (s_supbrut_h >= 1.1 * s_supbrut_mwh);
	SUPMW_13  = (s_supbrut_h < 1.3 * s_supbrut_mwh) and (s_supbrut_h >= 1.2 * s_supbrut_mwh);
	SUPMW_14  = (s_supbrut_h < 1.4 * s_supbrut_mwh) and (s_supbrut_h >= 1.3 * s_supbrut_mwh);
	SUPMW_15  = (s_supbrut_h < 1.5 * s_supbrut_mwh) and (s_supbrut_h >= 1.4 * s_supbrut_mwh);
	SUPMW_16  = (s_supbrut_h < 1.6 * s_supbrut_mwh) and (s_supbrut_h >= 1.5 * s_supbrut_mwh);
	SUPMW_17  = (s_supbrut_h < 1.7 * s_supbrut_mwh) and (s_supbrut_h >= 1.6 * s_supbrut_mwh);
	SUPMW_18  = (s_supbrut_h < 1.8 * s_supbrut_mwh) and (s_supbrut_h >= 1.7 * s_supbrut_mwh);
	SUPMW_19  = (s_supbrut_h < 1.9 * s_supbrut_mwh) and (s_supbrut_h >= 1.8 * s_supbrut_mwh);
	SUPMW_20  = (s_supbrut_h < 2.0 * s_supbrut_mwh) and (s_supbrut_h >= 1.9 * s_supbrut_mwh);
	SUPMW_20p =                                         (s_supbrut_h >= 2.0 * s_supbrut_mwh);
run;
data b; set dataA; run;
proc sort data = b; by siren; run;
proc means data = b noprint;
		by siren;
		var PB SMIC_05l SMIC_06 SMIC_07 SMIC_08 SMIC_09 SMIC_10 SMIC_11a SMIC_11b SMIC_12 SMIC_13 SMIC_14 SMIC_15 SMIC_16 SMIC_17 SMIC_18 SMIC_19 SMIC_20 SMIC_20p;
		output out = postes_smic_bins (drop = _type_ _freq_)
		sum        = postes_smicpb postes_smic05l postes_smic06 postes_smic07 postes_smic08 postes_smic09 postes_smic10 postes_smic11a postes_smic11b postes_smic12 postes_smic13 postes_smic14 postes_smic15 postes_smic16 postes_smic17 postes_smic18 postes_smic19 postes_smic20 postes_smic20p;
run;
data b; set dataA; run;
proc sort data = b; by siren; run;
proc means data = b noprint;
		by siren;
		var SUPMWPB SUPMW_05l SUPMW_06 SUPMW_07 SUPMW_08 SUPMW_09 SUPMW_10 SUPMW_11a SUPMW_11b SUPMW_12 SUPMW_13 SUPMW_14 SUPMW_15 SUPMW_16 SUPMW_17 SUPMW_18 SUPMW_19 SUPMW_20 SUPMW_20p;
		output out = postes_supmw_bins (drop = _type_ _freq_)
		sum        = postes_supmwpb postes_supmw05l postes_supmw06 postes_supmw07 postes_supmw08 postes_supmw09 postes_supmw10 postes_supmw11a postes_supmw11b postes_supmw12 postes_supmw13 postes_supmw14 postes_supmw15 postes_supmw16 postes_supmw17 postes_supmw18 postes_supmw19 postes_supmw20 postes_supmw20p;
run;
data dataA; set dataA;
    PBhrs       = PB*nbheur;
    SMIC_05lhrs = SMIC_05l*nbheur;
    SMIC_06hrs  = SMIC_06*nbheur;
    SMIC_07hrs  = SMIC_07*nbheur;
    SMIC_08hrs  = SMIC_08*nbheur;
    SMIC_09hrs  = SMIC_09*nbheur;
    SMIC_10hrs  = SMIC_10*nbheur;
    SMIC_11ahrs = SMIC_11a*nbheur;
	SMIC_11bhrs = SMIC_11b*nbheur;
    SMIC_12hrs  = SMIC_12*nbheur;
    SMIC_13hrs  = SMIC_13*nbheur;
    SMIC_14hrs  = SMIC_14*nbheur;
    SMIC_15hrs  = SMIC_15*nbheur;
    SMIC_16hrs  = SMIC_16*nbheur;
    SMIC_17hrs  = SMIC_17*nbheur;
	SMIC_18hrs  = SMIC_18*nbheur;
	SMIC_19hrs  = SMIC_19*nbheur;
	SMIC_20hrs  = SMIC_20*nbheur;
	SMIC_20phrs = SMIC_20p*nbheur;
    SUPMWPBhrs   = SUPMWPB*nbheur;
    SUPMW_05lhrs = SUPMW_05l*nbheur;
    SUPMW_06hrs  = SUPMW_06*nbheur;
    SUPMW_07hrs  = SUPMW_07*nbheur;
    SUPMW_08hrs  = SUPMW_08*nbheur;
    SUPMW_09hrs  = SUPMW_09*nbheur;
    SUPMW_10hrs  = SUPMW_10*nbheur;
    SUPMW_11ahrs = SUPMW_11a*nbheur;
	SUPMW_11bhrs = SUPMW_11b*nbheur;
    SUPMW_12hrs  = SUPMW_12*nbheur;
    SUPMW_13hrs  = SUPMW_13*nbheur;
    SUPMW_14hrs  = SUPMW_14*nbheur;
    SUPMW_15hrs  = SUPMW_15*nbheur;
    SUPMW_16hrs  = SUPMW_16*nbheur;
    SUPMW_17hrs  = SUPMW_17*nbheur;
	SUPMW_18hrs  = SUPMW_18*nbheur;
	SUPMW_19hrs  = SUPMW_19*nbheur;
	SUPMW_20hrs  = SUPMW_20*nbheur;
	SUPMW_20phrs = SUPMW_20p*nbheur;
run;
data b; set dataA; run;
proc sort data = b; by siren; run;
proc means data = b noprint;
		by siren;
		var PBhrs SMIC_05lhrs SMIC_06hrs SMIC_07hrs SMIC_08hrs SMIC_09hrs SMIC_10hrs SMIC_11ahrs SMIC_11bhrs SMIC_12hrs SMIC_13hrs SMIC_14hrs SMIC_15hrs SMIC_16hrs SMIC_17hrs SMIC_18hrs SMIC_19hrs SMIC_20hrs SMIC_20phrs;
		output out = hrs_smic_bins (drop = _type_ _freq_)
		sum        = hrs_smicpb hrs_smic05l hrs_smic06 hrs_smic07 hrs_smic08 hrs_smic09 hrs_smic10 hrs_smic11a hrs_smic11b hrs_smic12 hrs_smic13 hrs_smic14 hrs_smic15 hrs_smic16 hrs_smic17 hrs_smic18 hrs_smic19 hrs_smic20 hrs_smic20p;
run;
data b; set dataA; run;
proc sort data = b; by siren; run;
proc means data = b noprint;
		by siren;
		var SUPMWPBhrs SUPMW_05lhrs SUPMW_06hrs SUPMW_07hrs SUPMW_08hrs SUPMW_09hrs SUPMW_10hrs SUPMW_11ahrs SUPMW_11bhrs SUPMW_12hrs SUPMW_13hrs SUPMW_14hrs SUPMW_15hrs SUPMW_16hrs SUPMW_17hrs SUPMW_18hrs SUPMW_19hrs SUPMW_20hrs SUPMW_20phrs;
		output out = hrs_supmw_bins (drop = _type_ _freq_)
		sum        = hrs_supmwpb hrs_supmw05l hrs_supmw06 hrs_supmw07 hrs_supmw08 hrs_supmw09 hrs_supmw10 hrs_supmw11a hrs_supmw11b hrs_supmw12 hrs_supmw13 hrs_supmw14 hrs_supmw15 hrs_supmw16 hrs_supmw17 hrs_supmw18 hrs_supmw19 hrs_supmw20 hrs_supmw20p;
run;
data b; set dataA;
	E = 1;
run;
proc sort data = b; by siren; run;
proc means data = b noprint;
		by siren;
		var E nbheur;
		output out = tpostes (drop = _type_ _freq_)
		sum        = totpostes tothrs;
run;
data dataA; set dataA;
	codgeo = comt;
run;
data dataA; set dataA;
	drop comt;
run;
data dataA; set dataA;
	rename codgeo = comt;
run;
/* All policy variables have already been absorbed into the firm-level wage-bin totals. */
data dataB; set dataA;
	keep siren;
run;
proc sort data = dataB; by siren; run;
data dataB; set dataB; by siren;
	if first.siren;
run;
proc sort data = dataB; by siren; run;
proc sort data = postes_smic_bins; by siren; run;
proc sort data = postes_supmw_bins; by siren; run;
proc sort data = hrs_smic_bins; by siren; run;
proc sort data = hrs_supmw_bins; by siren; run;
proc sort data = tpostes; by siren; run;
data dataB; merge dataB postes_smic_bins postes_supmw_bins hrs_smic_bins hrs_supmw_bins tpostes; by siren; run;
data dataB; set dataB;
	year = &year.;
run;
/* Export only the wage-bin counts and denominators read by the retained Table 5 code. */
data dataB; set dataB;
	keep siren year
	     postes_smicpb postes_smic05l postes_smic06 postes_smic07 postes_smic08 postes_smic09 postes_smic10 postes_smic11a postes_smic11b postes_smic12 postes_smic13 postes_smic14 postes_smic15 postes_smic16 postes_smic17 postes_smic18 postes_smic19 postes_smic20 postes_smic20p
	     postes_supmwpb postes_supmw05l postes_supmw06 postes_supmw07 postes_supmw08 postes_supmw09 postes_supmw10 postes_supmw11a postes_supmw11b postes_supmw12 postes_supmw13 postes_supmw14 postes_supmw15 postes_supmw16 postes_supmw17 postes_supmw18 postes_supmw19 postes_supmw20 postes_supmw20p
	     hrs_smicpb hrs_smic05l hrs_smic06 hrs_smic07 hrs_smic08 hrs_smic09 hrs_smic10 hrs_smic11a hrs_smic11b hrs_smic12 hrs_smic13 hrs_smic14 hrs_smic15 hrs_smic16 hrs_smic17 hrs_smic18 hrs_smic19 hrs_smic20 hrs_smic20p
	     hrs_supmwpb hrs_supmw05l hrs_supmw06 hrs_supmw07 hrs_supmw08 hrs_supmw09 hrs_supmw10 hrs_supmw11a hrs_supmw11b hrs_supmw12 hrs_supmw13 hrs_supmw14 hrs_supmw15 hrs_supmw16 hrs_supmw17 hrs_supmw18 hrs_supmw19 hrs_supmw20 hrs_supmw20p
	     totpostes tothrs;
run;
proc datasets library = work;
	delete postes_smic_bins postes_supmw_bins hrs_smic_bins hrs_supmw_bins tpostes;
run;
proc datasets lib = work memtype = data;
	modify dataB;
	attrib _all_ label = '';
	attrib _all_ format = ;
run;
	PROC EXPORT DATA = dataB
		OUTFILE = "&root\output\generated\Output_data\For_4_SAS_ORGANIZATIONS\STATA\calibration_wagebins_lp02&year..dta"
		DBMS = DTA LABEL REPLACE;
	RUN;
proc datasets library = work;
	delete dataA dataB b;
run;
%mend;
%dads_calibration_moments2;
